#!/bin/sh


display_usage() { 
	echo "$0 - sorts a file by <index>, and then <rank>, and filters out the top ranking line for each <index> (output: file.top)" 
	echo -e "\nUsage: $0 file index rank\n" 
}
 
# if less than four arguments supplied, display usage 
if [  $# -le 4 ] 
	then 
		display_usage
	exit 1
fi 


sort -k"$2","$2" -k"$3","$3" "$1" | awk -v i=$2 '{if ($i!=PREV) print $0; PREV=$i}' > "$1".top

